import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/layouts/appLayout";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  if (cookieStore.has("user")) {
    var dataStore = JSON.parse(cookieStore.get("user")?.value ?? "");
  }
  return (
    <html lang="en">
      <body className="">
        <AppLayout user={dataStore}>{children}</AppLayout>
      </body>
    </html>
  );
}
